"""
STR (Suspicious Transaction Report) generator — auto-fills the FIU-IND
format from case data and outputs a PDF with evidentiary hashes.
"""
import hashlib
from pathlib import Path
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas

REPORT_DIR = Path("ml_artifacts") / "reports"


def generate_str_report(case_id: str) -> str:
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    output_path = REPORT_DIR / f"STR_{case_id}.pdf"

    # TODO: pull real case data (entities, transactions, risk scores) from Postgres
    case_data = _get_case_data(case_id)
    evidentiary_hash = _compute_evidentiary_hash(case_data)

    c = canvas.Canvas(str(output_path), pagesize=A4)
    width, height = A4

    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, height - 60, "SUSPICIOUS TRANSACTION REPORT (STR)")
    c.setFont("Helvetica", 10)
    c.drawString(50, height - 90, "Format: FIU-IND compliant draft — generated by Project Trinetra")

    y = height - 130
    c.setFont("Helvetica-Bold", 11)
    c.drawString(50, y, f"Case ID: {case_id}")
    y -= 20
    c.drawString(50, y, f"Evidentiary Hash (SHA-256): {evidentiary_hash[:32]}...")
    y -= 30

    c.setFont("Helvetica", 10)
    for entity in case_data.get("flagged_entities", []):
        c.drawString(50, y, f"- Entity {entity['id']}: risk={entity['risk_score']}, flags={entity['flags']}")
        y -= 15

    c.save()
    return str(output_path)


def _get_case_data(case_id: str) -> dict:
    return {"case_id": case_id, "flagged_entities": []}


def _compute_evidentiary_hash(case_data: dict) -> str:
    return hashlib.sha256(str(case_data).encode()).hexdigest()
